### PR TITLE
new logo proposal

### PR DESCRIPTION
**Pull request by ihtiht**
I wanted to design a logo for this new add-on. I wanted to emphasize the N in the news headline. I designed a very simple logo because it had to look good in small sizes. I hope you like it.

### CODE REVIEW

**Comment by FengShangWuQi** [comment]
Hi, @ihtiht

I'm very glad to see this PR, thank you very much, and I also think the logo is full of creativity :+1:, I just have one question,  do you think swaping the color would be better?

just like

image

because I can't fell the N obviously, what do you think?

**Comment by ihtiht** [comment]
I am honored to contribute to the project. I changed the color as you like. 


news  

Is that what you want?

If so, I will send a new PR.

**Comment by ihtiht** [comment]
These emphasize the letter "N" more.  Which of these suggestions do you like? 


news

**Comment by FengShangWuQi** [comment]
[shake hands]

I prefer 1, how about you?

2018-04-16 20:39 GMT+08:00 ihtiht <notifications@github.com>:

**Comment by ihtiht** [comment]
Me too.. I think 1 looks better. 




news1

**Comment by FengShangWuQi** [comment]
Looking forward to your PR.

I created a issue(#13) for this before, and I will solve other issues
urgent today together,  a new version will be published tomorrow.

Thanks.

2018-04-16 20:56 GMT+08:00 ihtiht <notifications@github.com>:

**Pull request closed without merging**
